/* cmdline.h */

/* File autogenerated by gengetopt version 2.10  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "pbxbuild"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "0.5"
#endif

struct gengetopt_args_info
{
  char * project_arg;	/* The Project to build (.xcode, .xcodeproj).  */
  int generate_makefile_only_flag;	/* This only generates project makefiles without running make (default=off).  */
  int debug_flag;	/* Turn on debug logging (default=off).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int project_given ;	/* Whether project was given.  */
  int generate_makefile_only_given ;	/* Whether generate-makefile-only was given.  */
  int debug_given ;	/* Whether debug was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
