#
# GNUmakefile - Generated by ProjectCenter
#

GNUSTEP_INSTALLATION_DOMAIN=SYSTEM

include $(GNUSTEP_MAKEFILES)/common.make

#
# Tool
#
VERSION = 0.1
PACKAGE_NAME = pbxbuild
TOOL_NAME = pbxbuild
pbxbuild_TOOL_ICON = 

#
# Libraries
#
pbxbuild_TOOL_LIBS += 

#
# Resource files
#
pbxbuild_RESOURCE_FILES = \
Resources/Info-gnustep.plist

#
# Header files
#
pbxbuild_HEADER_FILES = \
cmdline.h \
PBMakefileGenerator.h \
PBPbxProject.h \
PBPbxNativeTarget.h \
PBDevelopmentHelper.h \
PBPbxGroup.h

#
# Class files
#
pbxbuild_OBJC_FILES = \
PBMakefileGenerator.m \
PBPbxProject.m \
PBPbxNativeTarget.m \
PBDevelopmentHelper.m \
PBPbxGroup.m

#
# C files
#
pbxbuild_C_FILES = \
cmdline.c 

pbxbuild_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
