#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Tool
#
VERSION = 0.1
PACKAGE_NAME = pbxbuild
TOOL_NAME = pbxbuild
pbxbuild_TOOL_ICON = 


#
# Resource files
#
pbxbuild_RESOURCE_FILES = \
Resources/Info-gnustep.plist \


#
# Header files
#
pbxbuild_HEADER_FILES = \
cmdline.h \
PBProjectGenerator.h \
PBMakefileGenerator.h \
PBPbxProject.h \
PBPbxNativeTarget.h \
PBDevelopmentHelper.h \
PBPbxGroup.h

#
# Class files
#
pbxbuild_OBJC_FILES = \
PBProjectGenerator.m \
PBMakefileGenerator.m \
PBPbxProject.m \
PBPbxNativeTarget.m \
PBDevelopmentHelper.m \
PBPbxGroup.m

#
# Other sources
#
pbxbuild_C_FILES = \
cmdline.c 

pbxbuild_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
